[build]
target = "crates/marble-client/index.html"
dist = "dist"
minify = "on_release"

[watch]
watch = ["crates/marble-client", "crates/marble-core"]
ignore = ["target", "crates/marble-server"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"
